version: 2
general:
  branches:
    ignore:
      - /binary-.*/

jobs:
  build:
    docker:
      - image: autozimu/languageclientneovim
    steps:
      - checkout
      - run: make integration-test

# vim: tabstop=2
