#!/bin/bash
name=$1
path="$HOME/.konfig/scripts/tmux.d/$name.tmuxrc"

if !(tmux has-session -t "$name" 2> /dev/null); then
  tmux start                     \;\
    set -g set-remain-on-exit on \;\
    new-session -d -s $name
  tmux source-file $path
fi

if [ ! -f $path ]; then
    exit 1
fi

tmux source-file "$HOME/.tmux.conf" > /dev/null
tmux attach -t $name
